workflows:
    - .github/**/*
repo:
    - ./*
client:
    - packages/client/**/*
common:
    - packages/common/**/*
server:
    - packages/server/**/*
    - packages/service_*/**/*
documentation:
    - "**/*.md"
