name: Dependency checker

on: [pull_request]

jobs:
  dependency_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout	
        uses: actions/checkout@v2	
      - name: Check dependencies
        uses: juanigalan91/monorepolyser@0.2.6
        with:
          check-dependencies: true
          include-main-package-json: true
          only-warn: true
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
